# Generated by Django 3.0 on 2021-04-08 06:35

from django.db import migrations, models
import files.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audiobook_title', models.CharField(max_length=100)),
                ('audiobook_author', models.CharField(max_length=100)),
                ('audiobook_narrator', models.CharField(max_length=100)),
                ('audiobook_duration', models.PositiveIntegerField()),
                ('upload_time', models.DateTimeField(validators=[files.models.validate_date])),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podcast_title', models.CharField(max_length=100)),
                ('podcast_duration', models.PositiveIntegerField()),
                ('upload_time', models.DateTimeField(validators=[files.models.validate_date])),
                ('podcast_host', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=100)),
                ('song_duration', models.PositiveIntegerField()),
                ('upload_time', models.DateTimeField(validators=[files.models.validate_date])),
            ],
        ),
    ]
